# Generated by Django 3.1.4 on 2020-12-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_amenity_amenitycategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='amenitycategory',
            options={'verbose_name_plural': 'AmenityCategories'},
        ),
    ]
