# Generated by Django 3.1.4 on 2020-12-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201215_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlineitem',
            name='number_of_nights',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
