# Generated by Django 3.1.4 on 2020-12-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_email'),
        ('checkout', '0006_auto_20201219_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='profiles.userprofile'),
        ),
    ]
