# Generated by Django 3.1.4 on 2020-12-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='intro',
            field=models.TextField(),
        ),
    ]
