# Generated by Django 3.1.4 on 2020-12-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_info', '0002_auto_20201211_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='link_to_google_maps',
            field=models.URLField(max_length=500),
        ),
    ]
